### ISSUE TITLE
Update the Azure DevOps feature docs for setting the ARM output as Azure DevOps variables

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#212]
**Is your feature request related to a problem? Please describe.**
The current feature documentation that explains how the ARM output can be set as variables in a variable group within an Azure DevOps team project, only goes over the pure basics of the script. This can lead to lots of support questions on 'how this script can be used in the real world'.

**Describe the solution you'd like**
We should consider updating the feature docs with the following additions:
- [ ] Explain the required permissions for setting variables in Azure DevOps variables groups (+ screenshot).
- [ ] Show an YAML example where the ARM outputs are set as an environment variable (markdown code sample).
Something in the like of:
```yaml
- powershell:
    Set-AzDevOpsArmOutputsToVariableGroup `
      -VariableGroupName "Infra.DEV" `
      -ArmOutputsEnvironmentVariableName "ArmOutputs"
  displayName: 'Update variable group of project'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

**Additional context**
Was first discovered by @spasal in #210
