### ISSUE TITLE
Set-AzDevOpsArmOutputs:  cannot bind argument to parameter 'InputObject' because it is null

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#272]
**Describe the bug**
I want to expose ARM outputs to environment variables in my devops pipeline, but I receive this error:

> Set-AzDevOpsArmOutputs:  cannot bind argument to parameter 'InputObject' because it is null

**To Reproduce**

I have a `AzureResourceGroupDeployment@2` task which deploys an ARM template.  The next task is a Powershell task which executes the Arcus `Set-AzDevOpsArmOutputs` script.

```yaml
- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy resources for curated dataset builder for PLC data'
  inputs:
    azureSubscription: ${{parameters.azureResourceManagerConnection}}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{parameters.resourceGroupName}}
    location: ${{parameters.deployLocation}}
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/package_build/myfile.arm'
    csmParametersFile: '$(Pipeline.Workspace)/package_build/myfile.parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: ArmOutputs

- task: PowerShell@2
  displayName: 'Promote Azure resource outputs to pipeline variables'
  inputs:  
    targetType: 'inline'
    script: |          
      Install-Module -Name Arcus.Scripting.DevOps -Force
      Set-AzDevOpsArmOutputsToPipelineVariables    
```

I'm faced with this error:
```
Get ARM outputs from 'ArmOutputs' environment variable
Set-AzDevOpsArmOutputs.ps1: Cannot bind argument to parameter 'InputObject' because it is null.

##[error]PowerShell exited with code '1'.
```

What is the 'inputObject' parameter ?
