### ISSUE TITLE
Writing ARM outputs to YAML file (instead of, currently, Azure DevOps variable group)

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#286]
**Is your feature request related to a problem? Please describe.**
Currently, we have in our Azure DevOps module some functionality to write the ARM outputs to Azure DevOps variable groups but not yet to YAML configuration files.

**Describe the solution you'd like**
Adds functionality to write the ARM outputs to an YAML file.

**Additional context**
Follow-up of https://github.com/Codit/codit-academy/issues/132#issuecomment-1072259534

**Comment by stijnmoreels** [comment]
A reminder for my fellow partner @pim-simons 😉 .

**Comment by fgheysels** [comment]
I'm actually very much doubting if this is something that we want.
This would mean that pipeline-runs modify the contents of your  code-base, as the yaml files are stored in your repository.

Actually, I would try to avoid using ARM outputs alltogether in CI/CD pipelines, and if you really need them, I'd just make them available in a non-persistent way: in variables that are scoped to my pipeline. (And thus even not write them to variable groups).

**Comment by stijnmoreels** [comment]
> I'm actually very much doubting if this is something that we want. This would mean that pipeline-runs modify the contents of your code-base, as the yaml files are stored in your repository.
> 
> Actually, I would try to avoid using ARM outputs alltogether in CI/CD pipelines, and if you really need them, I'd just make them available in a non-persistent way: in variables that are scoped to my pipeline. (And thus even not write them to variable groups).
> 
> I used ARM outputs in the past as well, but I now tend to avoid them alltogether. When I need a certain property of something that was deployed in my pipeline, I now use Azure CLI script to look-up that value, instead of having it outputted in an ARM template, especially when we're talking about sensitive information.

Honestly, I'm way outside this scope of technology 😅 , so I can't really give my view on things bc I've have actually no idea how these things are used, or even what ARM templates are actually for. I'll let @pim-simons handle this. 😄 
If it's indeed about sensitive information, then I'm all for removing it from public spaces. 👍

**Comment by pim-simons** [comment]
> I'm actually very much doubting if this is something that we want. This would mean that pipeline-runs modify the contents of your code-base, as the yaml files are stored in your repository.
> 
> Actually, I would try to avoid using ARM outputs alltogether in CI/CD pipelines, and if you really need them, I'd just make them available in a non-persistent way: in variables that are scoped to my pipeline. (And thus even not write them to variable groups).
> 
> I used ARM outputs in the past as well, but I now tend to avoid them alltogether. When I need a certain property of something that was deployed in my pipeline, I now use Azure CLI script to look-up that value, instead of having it outputted in an ARM template, especially when we're talking about sensitive information.

Some good points 👍🏻 
Writing to a file in your code-base will be a challenge indeed, since you cannot simply change this in your `main` branch you would have to create a new branch for this, this would make the script a lot more complex.

Regarding:
> I used ARM outputs in the past as well, but I now tend to avoid them alltogether. When I need a certain property of something that was deployed in my pipeline, I now use Azure CLI script to look-up that value, instead of having it outputted in an ARM template, especially when we're talking about sensitive information.

I suppose you get the values using Azure CLI and then pass them along using a variable? Do you maybe have an example of this you can share?

**Comment by fgheysels** [comment]
> I suppose you get the values using Azure CLI and then pass them along using a variable to your ARM/Bicep? Do you maybe have an example of this you can share?

Actually, it is quite simple.
The below sample shows how I retrieve ACR credentials and put them in a variable that I then can use in another task.

```yaml
- task: AzureCLI@2
  displayName: 'Get ACR credentials'
  inputs:
      azureSubscription: ...
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'    
      errorActionPreference: 'stop'
      inlineScript: |  
        $registryName = "$(ContainerRegistry.Address)".TrimEnd('.azurecr.io')
          
        $containerCreds = az acr credential show --name $registryName --resource-group rg-myresourcegroup | ConvertFrom-Json

        $acrPwd = $containerCreds.passwords[0].value
        Write-Host "##vso[task.setvariable variable=ContainerRegistry.Password;issecret=true]$acrPwd"
```
